### ISSUE TITLE
大佬,我想问一下mybatis版本的为什么取消了mapstruct

### ISSUE THREAD

**Issue by 1332987** [elunez/eladmin-mp#11]
大佬,我想问一下mybatis版本的为什么取消了mapstruct这个依赖

**Comment by elunez** [comment]
jpa 版本用到了 @Query  注解，不能控制返回的参数。所以会用到 mapstruct 转换下，去除掉不需要返回的参数。
mp 的话直接能控制需要返回的参数，所以也就不需要用到 mapstruct 了，把 mapstruct 去掉，对刚学习的开发者也会更友好。当然有些业务可能会用到 mapstruct，这种情况把 mapstruct 加上去就行了。
