### ISSUE TITLE
字典详情-删除，报空指针

### ISSUE THREAD

**Issue by jiangqx95** [elunez/eladmin-mp#15]
![image](https://github.com/elunez/eladmin-mp/assets/108656350/d060a661-4c86-41ec-ba80-2c3c4ced1fd0)

**Comment by elunez** [comment]
已经解决了，查看最近提交

**Comment by jiangqx95** [comment]
看了提交日志，改之前编辑会报错，但改了后删除就会报错，这儿取id的方式得根据不同操作判断下
![image](https://github.com/elunez/eladmin-mp/assets/108656350/78cd3d39-9e1a-481f-a23e-c27199002cd7)

**Comment by elunez** [comment]
感谢，已修复
