### ISSUE TITLE
非必填项前端却进行了必填校验

### ISSUE THREAD

**Issue by jiangqx95** [elunez/eladmin-mp#16]
![image](https://github.com/elunez/eladmin-mp/assets/108656350/86d5f019-a0ea-4c12-aafd-600dadf80997)
![image](https://github.com/elunez/eladmin-mp/assets/108656350/58563d20-3c2a-4c71-89c3-e8c4410d3b53)

**Comment by elunez** [comment]
这个是必填的，换了种提示而已

**Comment by jiangqx95** [comment]
但是后端好像没加注解校验是否为空，前端也没有*号标识必填
![image](https://github.com/elunez/eladmin-mp/assets/108656350/fe741c63-866e-465a-a582-166d0bf3906e)
