### ISSUE TITLE
401死循环

### ISSUE THREAD

**Issue by jiangqx95** [elunez/eladmin-mp#24]
当已经401了，调用logout接口也是401，就会在这里死循环
![image](https://github.com/elunez/eladmin-mp/assets/108656350/d42d971c-8e8e-4ddb-b88e-0d57cffb4500)
![image](https://github.com/elunez/eladmin-mp/assets/108656350/ffc5dd0c-2626-4720-9aec-ea85b73677bf)

**Comment by shanshizi** [comment]
token过期, 401死循环bug
catch((err) => {
  Notification.error({
    title: err,
    duration: 5000
  })
  Cookies.set('point', 401)
  location.reload()
})

**Comment by shanshizi** [comment]
![image](https://github.com/elunez/eladmin-mp/assets/42896665/f0ab14c2-56a4-4522-9592-5a3fc48e32f6)

**Comment by shanshizi** [comment]
邮件已自动接收
