### ISSUE TITLE
关于之前我提的一个Issiue

### ISSUE THREAD

**Issue by 846027729** [elunez/eladmin-mp#27]
之前我提了一个Issue，是关于前端界面左侧菜单和tagsView在浏览器缩放至一定条件时会出现原生滚动条，如图：
![image](https://github.com/elunez/eladmin-mp/assets/64539202/0099a141-1768-4cb0-9537-af49456e9501)
最近闲来无事，解决了一下：
1、在sidebar.css28行.scrollbar-wrapper样式下加  &::-webkit-scrollbar { width: 17px; }，解决右侧菜单栏垂直滚动条问题；
![image](https://github.com/elunez/eladmin-mp/assets/64539202/42fc0ab6-52c4-4f3f-b9bb-a5b4bffcd208)
2、在ScrollPanel.vue样式.el-scrollbar__wrap下添加：overflow: hidden;
![image](https://github.com/elunez/eladmin-mp/assets/64539202/3e24d399-2a3b-4e03-b6c1-cb95ad7650ca)

**Comment by elunez** [comment]
好的，谢谢，等国庆后我处理下

**Comment by 846027729** [comment]
![image](https://github.com/elunez/eladmin-mp/assets/64539202/157401d7-38c8-4dee-bbdf-868db4b529db)
这是我之前提的：el-scrollbar__wrap元素上已经设置了margin-bottom: -17px; margin-right: -17px; 所以在此基础上控制住原生滚动条的宽度即可；第二个ScrollPanel.vue样式.el-scrollbar__wrap下添加：overflow: hidden
隐藏TagView垂直和水平滚动条
