### ISSUE TITLE
定时任务分布式部署时重复执行问题

### ISSUE THREAD

**Issue by maqun0425** [elunez/eladmin-mp#35]
环境：
数据库节点1个
Redis节点1个
项目节点（springboot工程）2个
操作：
配置一个定时任务每分钟执行一次，观察发现两个项目每分钟都在执行，数据库查看定时任务日志也显示每分钟执行了2次

**Comment by Tingnichui** [comment]
你两个项目节点的话，对于定时任务来说就是两个单独的项目，你需要在定时任务搞个分布式锁，用redist做一个，拿到锁之后才能执行任务

**Comment by elunez** [comment]
> 环境： 数据库节点1个 Redis节点1个 项目节点（springboot工程）2个 操作： 配置一个定时任务每分钟执行一次，观察发现两个项目每分钟都在执行，数据库查看定时任务日志也显示每分钟执行了2次

已更新分布式支持
