### ISSUE TITLE
邮件功能异常bug

### ISSUE THREAD

**Issue by catandpanda** [elunez/eladmin-mp#36]
1. 确少依赖，导致无法获取到邮件模版<dependency>
            <groupId>org.apache.velocity</groupId>
            <artifactId>velocity-engine-core</artifactId>
            <version>2.2</version>
        </dependency>
2. 在修改邮箱时，比对验证码无效，原因：存入redis的key以旧邮箱为key，取的时候以新邮箱为key
3. 修改邮箱成功后没有正确保存新邮箱，原因：还是存的原来的邮箱地址，字段引入错误

**Comment by elunez** [comment]
我这边没加依赖, 可以正常收到修改邮箱的邮件
```
org.apache.velocity
velocity-engine-core
2.2
```
