### ISSUE TITLE
项目启动后，首次登录比较慢

### ISSUE THREAD

**Issue by jiangqx95** [elunez/eladmin-mp#5]
![微信图片_20230705113959](https://github.com/elunez/eladmin-mp/assets/108656350/a24d171f-cb31-45c5-badd-4ae0edf46769)

启动项目首次登录比较慢，后面再登录就正常了，看日志是加载了yauua这个插件
我的处理方式是项目启动后，程序自动去调下登录接口，后面登录就快了，不知道有没有更好的处理方式。

**Comment by Jeffery186** [comment]
Redis首次使用会建立连接，这个过程比较慢

**Comment by elunez** [comment]
> Redis首次使用会建立连接，这个过程比较慢

这个不是 Redis ，这个是一个 ua 识别依赖，首次访问 StringUtil 的时候会进行初始化，这个过程慢。
现在已经替换为 hutool 工具包获取 ua 信息了，就不存在慢的问题了
