### ISSUE TITLE
配置增加是否开启验证码选项

### ISSUE THREAD

**Issue by jiangqx95** [elunez/eladmin-mp#7]
项目进行安全扫描时，会有关闭验证码的场景需求，可增加此选项来灵活配置

![image](https://github.com/elunez/eladmin-mp/assets/108656350/d8bf1395-5f3b-4167-b411-594e182ad7ff)
![image](https://github.com/elunez/eladmin-mp/assets/108656350/f0fef141-5e64-4f93-804c-a23bfeba40d5)
![image](https://github.com/elunez/eladmin-mp/assets/108656350/1a820440-b317-4464-b70f-135a4d447e10)
![image](https://github.com/elunez/eladmin-mp/assets/108656350/4e3d2a85-b4fd-42a4-89c3-5d7950594c35)

**Comment by elunez** [comment]
暂不考虑增加这个功能
